

services:
  kilosale_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "${DB_NAME_MAIN},${DB_NAME_MONEY},${DB_NAME_KYC}"

    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  kilosale_main_service:
    build:
      context: ./kilosale_main_service
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    depends_on:
      - kilosale_db
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "${PORT_ADMINER}:8080"
    depends_on:
      - kilosale_db
    
  
  # kilosale_kyc_service:
  #   context: .
  #   dockerfile: kilosale_kyc_service/Dockerfile
  #   ports:
  #     - "${PORT_KYC}:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - kilosale_db
  # kilosale_money_service:
  #   context: .
  #   dockerfile: kilosale_money_service/Dockerfile
  #   ports:
  #     - "${PORT_MONEY}:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - kilosale_db

volumes:
  db_data: